In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\samru\SQL Project\advanced_sql_ecommerce_project.csv")

In [4]:
df.head(5)

,order_id,customer_id,order_date,city,product_category,quantity,price_per_unit,total_amount,discount_percent,discount_amount,final_amount,payment_method
0,1,CUST1094,2023-11-24,Mumbai,Clothing,1,404,404,10,40.4,363.6,UPI
1,2,CUST1011,2023-02-22,Pune,Electronics,5,912,4560,20,912.0,3648.0,Net Banking
2,3,CUST1091,2023-04-22,Chennai,Clothing,2,4339,8678,20,1735.6,6942.4,Credit Card
3,4,CUST1000,2023-11-29,Chennai,Home,5,3636,18180,5,909.0,17271.0,Net Banking
4,5,CUST1013,2023-03-23,Mumbai,Home,4,2987,11948,10,1194.8,10753.2,UPI

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1000 non-null   int64
 1   customer_id       1000 non-null   object
 2   order_date        1000 non-null   object
 3   city              1000 non-null   object
 4   product_category  1000 non-null   object
 5   quantity          1000 non-null   int64
 6   price_per_unit    1000 non-null   int64
 7   total_amount      1000 non-null   int64
 8   discount_percent  1000 non-null   int64
 9   discount_amount   1000 non-null   float64
 10  final_amount      1000 non-null   float64
 11  payment_method    1000 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 93.9+ KB

In [6]:
df.isnull().sum()

order_id            0
customer_id         0
order_date          0
city                0
product_category    0
quantity            0
price_per_unit      0
total_amount        0
discount_percent    0
discount_amount     0
final_amount        0
payment_method      0
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.head(5)

,order_id,customer_id,order_date,city,product_category,quantity,price_per_unit,total_amount,discount_percent,discount_amount,final_amount,payment_method
0,1,CUST1094,2023-11-24,Mumbai,Clothing,1,404,404,10,40.4,363.6,UPI
1,2,CUST1011,2023-02-22,Pune,Electronics,5,912,4560,20,912.0,3648.0,Net Banking
2,3,CUST1091,2023-04-22,Chennai,Clothing,2,4339,8678,20,1735.6,6942.4,Credit Card
3,4,CUST1000,2023-11-29,Chennai,Home,5,3636,18180,5,909.0,17271.0,Net Banking
4,5,CUST1013,2023-03-23,Mumbai,Home,4,2987,11948,10,1194.8,10753.2,UPI

In [9]:
df.describe()

,order_id,quantity,price_per_unit,total_amount,discount_percent,discount_amount,final_amount
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.030000,2677.708000,8053.55400,10.200000,832.964850,7220.589150
std,288.819436,1.413187,1377.149212,5813.07857,7.163191,931.801024,5248.702634
min,1.000000,1.000000,201.000000,254.00000,0.000000,0.000000,215.900000
25%,250.750000,2.000000,1466.250000,3341.25000,5.000000,120.050000,2933.500000
50%,500.500000,3.000000,2755.500000,6520.50000,10.000000,512.475000,5884.000000
75%,750.250000,4.000000,3906.250000,11901.50000,15.000000,1207.762500,10708.950000
max,1000.000000,5.000000,4985.000000,24875.00000,20.000000,4604.000000,23322.500000

In [10]:
import pymysql
from sqlalchemy import create_engine
import pandas as pd

# MySQL connection details
username = "root"
password = "8830096357"
host = "localhost"
database = "ecommerce_sql_project"

# Correct engine
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}/{database}")

# Write DataFrame to MySQL
df.to_sql("orders", engine, if_exists="replace", index=False)

# Read sample data
data = pd.read_sql("SELECT * FROM orders LIMIT 5;", engine)
print(data)

   order_id customer_id  order_date     city product_category  quantity  \
0         1    CUST1094  2023-11-24   Mumbai         Clothing         1
1         2    CUST1011  2023-02-22     Pune      Electronics         5
2         3    CUST1091  2023-04-22  Chennai         Clothing         2
3         4    CUST1000  2023-11-29  Chennai             Home         5
4         5    CUST1013  2023-03-23   Mumbai             Home         4

   price_per_unit  total_amount  discount_percent  discount_amount  \
0             404           404                10             40.4
1             912          4560                20            912.0
2            4339          8678                20           1735.6
3            3636         18180                 5            909.0
4            2987         11948                10           1194.8

   final_amount payment_method
0         363.6            UPI
1        3648.0    Net Banking
2        6942.4    Credit Card
3       17271.0    Net Banking
4       10753.2            UPI